# Generated by Django 4.0.3 on 2022-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('order_no', models.IntegerField()),
                ('cust_id', models.EmailField(max_length=255)),
                ('item', models.TextField()),
                ('price', models.TextField(default='100')),
            ],
        ),
    ]
