# Generated by Django 4.0.3 on 2022-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
