# Generated by Django 4.0.3 on 2022-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_cart_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.TextField()),
                ('order_no', models.IntegerField()),
                ('cust_id', models.EmailField(max_length=255)),
                ('item', models.TextField()),
                ('price', models.TextField(default='100')),
            ],
        ),
    ]
