# Generated by Django 4.0.3 on 2022-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rec_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField(default='')),
                ('city', models.TextField()),
                ('pin', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
    ]
