# Generated by Django 3.2.7 on 2022-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='email',
        ),
        migrations.AddField(
            model_name='menu',
            name='uid',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
