# Generated by Django 3.2.7 on 2022-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hotel',
            field=models.TextField(default=''),
        ),
    ]
