# Generated by Django 3.2.7 on 2022-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('order_no', models.IntegerField()),
                ('cust_id', models.EmailField(max_length=255)),
                ('item', models.TextField()),
                ('price', models.TextField(default='100')),
                ('status', models.TextField()),
            ],
        ),
    ]
