# Generated by Django 4.0.3 on 2022-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
