# Generated by Django 4.0.3 on 2022-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
