# Generated by Django 4.0.3 on 2022-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menu_uid_alter_order_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_1',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
